### ISSUE TITLE
PopupWatcherLibrary.StopAllPopupWatchers may throw InvalidOperationException

### ISSUE THREAD

**Issue by ahoisl** [ranorex/Packages#30]
When there are more PopupWatcher entries active and you call PopupWatcherLibrary.StopAllPopupWatchers this will cause an InvalidOperationException to be thrown.

Actually, a unit test covers that situation, but it did not fail.

This was introduced with the fix for issue #22

**Comment by Didddy** [comment]
Thx for your help to fix that!
